### ISSUE TITLE
Time for TA only in playback file

### ISSUE THREAD

**Issue by andimik** [ChristopheJacquet/RdsSurveyor#25]
I just realized that the time for traffic events is only displayed correctly when using a playback file (see right window: 10:13:26 start and 10.14.24 end). In the live mode with RTL stick the time is a 4-digit number.

![grafik](https://user-images.githubusercontent.com/24510556/37244142-c2140456-2484-11e8-8d0c-cf77b6705bb8.png)

**Comment by andimik** [comment]
Any idea what goes wrong here?

**Comment by mvglasow** [comment]
I never dealt with this kind of thing when I wrote the plugin (all the plugin does is exchange commands and tuning status with the device, and supply a stream of RDS groups). It would be interesting to see what happens when the device is connected to another form of live input, e.g. a Si470x stick. I suspect it might affect other forms of live input as well.

**Comment by mvglasow** [comment]
Just tried the Si4701 stick: here I get proper start and end times. Will try with the SDR on my end.

**Comment by mvglasow** [comment]
Indeed, I get the same behavior with the SDR, no idea why. @ChristopheJacquet any ideas?

**Comment by mvglasow** [comment]
PS: same with the group analyzer. Si470x shows proper timestamps, SDR shows 4 digits.

**Comment by mvglasow** [comment]
Fix submitted as pull request #29.

**Comment by andimik** [comment]
I confirm this works. Sorry for the delay.
